/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.studentbiodata;

/**
 *
 * @author Rahul
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminHomePanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        addStudent = new javax.swing.JButton();
        removeStudent = new javax.swing.JButton();
        checkStudent = new javax.swing.JButton();
        displayAllStudents = new javax.swing.JButton();
        updateStudentDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminHomePanel.setLayout(new java.awt.CardLayout());

        addStudent.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        addStudent.setIcon(new javax.swing.ImageIcon("D:\\javaProjectEamcet\\studentBioData\\src\\images\\addStudent.png")); // NOI18N
        addStudent.setText("Add Student");
        addStudent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addStudent.setDisabledIcon(new javax.swing.ImageIcon("D:\\javaProjectEamcet\\studentBioData\\src\\images\\addStudent.png")); // NOI18N
        addStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        removeStudent.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        removeStudent.setIcon(new javax.swing.ImageIcon("D:\\javaProjectEamcet\\studentBioData\\src\\images\\removeStudent.png")); // NOI18N
        removeStudent.setText("Remove Student");
        removeStudent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        removeStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudentActionPerformed(evt);
            }
        });

        checkStudent.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        checkStudent.setIcon(new javax.swing.ImageIcon("D:\\javaProjectEamcet\\studentBioData\\src\\images\\displayStudent.png")); // NOI18N
        checkStudent.setText("Check Student");
        checkStudent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        checkStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkStudentActionPerformed(evt);
            }
        });

        displayAllStudents.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        displayAllStudents.setIcon(new javax.swing.ImageIcon("D:\\javaProjectEamcet\\studentBioData\\src\\images\\displayAll.png")); // NOI18N
        displayAllStudents.setText("Display All Students");
        displayAllStudents.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        displayAllStudents.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        displayAllStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAllStudentsActionPerformed(evt);
            }
        });

        updateStudentDetails.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        updateStudentDetails.setIcon(new javax.swing.ImageIcon("D:\\javaProjectEamcet\\studentBioData\\src\\images\\updateStudent.png")); // NOI18N
        updateStudentDetails.setText("Update Student Data");
        updateStudentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(checkStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(addStudent))
                .addGap(43, 43, 43)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayAllStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(updateStudentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(894, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(displayAllStudents, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(checkStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(updateStudentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 680, Short.MAX_VALUE))
        );

        homePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addStudent, displayAllStudents});

        adminHomePanel.add(homePanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(adminHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(adminHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateStudentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentDetailsActionPerformed
        UpdateStudentPanel usp = new UpdateStudentPanel();
        usp.setVisible(true);
        usp.AdminPanelReference(this);
        adminHomePanel.removeAll();
        adminHomePanel.add(usp);
        adminHomePanel.repaint();
        adminHomePanel.revalidate();
    }//GEN-LAST:event_updateStudentDetailsActionPerformed

    private void displayAllStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllStudentsActionPerformed
        DisplayAllStudentPanel dasp = new DisplayAllStudentPanel();
        dasp.setVisible(true);
        dasp.AdminPanelReference(this);
        adminHomePanel.removeAll();
        adminHomePanel.add(dasp);
        adminHomePanel.repaint();
        adminHomePanel.revalidate();

    }//GEN-LAST:event_displayAllStudentsActionPerformed

    private void checkStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStudentActionPerformed

        CheckStudentPanel csp = new CheckStudentPanel();
        csp.setVisible(true);
        csp.AdminPanelReference(this);
        adminHomePanel.removeAll();
        adminHomePanel.add(csp);
        adminHomePanel.repaint();
        adminHomePanel.revalidate();
    }//GEN-LAST:event_checkStudentActionPerformed

    private void removeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudentActionPerformed

        RemoveStudentPanel rsp = new RemoveStudentPanel();
        rsp.setVisible(true);
        rsp.AdminPanelReference(this);
        adminHomePanel.removeAll();
        adminHomePanel.add(rsp);
        adminHomePanel.repaint();
        adminHomePanel.revalidate();
    }//GEN-LAST:event_removeStudentActionPerformed

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed

        AddStudentPanel asp = new AddStudentPanel();
        
        asp.setVisible(true);
        asp.AdminPanelReference(this);
        adminHomePanel.removeAll();
        adminHomePanel.add(asp);
        adminHomePanel.repaint();
        adminHomePanel.revalidate();


    }//GEN-LAST:event_addStudentActionPerformed
  
   
   
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudent;
    public javax.swing.JPanel adminHomePanel;
    private javax.swing.JButton checkStudent;
    private javax.swing.JButton displayAllStudents;
    public javax.swing.JPanel homePanel;
    private javax.swing.JButton removeStudent;
    private javax.swing.JButton updateStudentDetails;
    // End of variables declaration//GEN-END:variables
}
