/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.studentbiodata;

import java.awt.Dimension;
import java.awt.Image;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rahul
 */
public class CheckStudentPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckStudentPanel
     */
    public CheckStudentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rollNumberLabel = new javax.swing.JLabel();
        checkBtn = new javax.swing.JButton();
        rollNumberCheckField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentData = new javax.swing.JTable();
        studentPhoto = new javax.swing.JLabel();
        checkBackBtn = new javax.swing.JButton();

        rollNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rollNumberLabel.setText("Roll Number");

        checkBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        checkBtn.setText("Check");
        checkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnActionPerformed(evt);
            }
        });

        studentData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        studentData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Details", "Values"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentData.setRowHeight(35);
        jScrollPane1.setViewportView(studentData);

        checkBackBtn.setText("Back");
        checkBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(840, 840, 840))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBackBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(studentPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(rollNumberLabel))
                        .addGap(63, 63, 63)
                        .addComponent(rollNumberCheckField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1270, 1270, 1270))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBackBtn)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rollNumberLabel)
                    .addComponent(rollNumberCheckField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(checkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(studentPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(791, 791, 791))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnActionPerformed
        studentPhoto.setText("");
        studentPhoto.setIcon(null);
        try {
            Connection con = GetConnection.createConnection();
            String query = "SELECT * FROM studentBiodata WHERE ROLLNUMBER = ?";
            PreparedStatement statement = con.prepareStatement(query);
            statement.setString(1, rollNumberCheckField.getText());
            ResultSet rs;

            rs = statement.executeQuery();

            DefaultTableModel tModel = (DefaultTableModel) studentData.getModel();
            Object[] values = {"Name", "Roll Number", "Father Name", "Mother Name", "Date Of Birth", "Gender", "Email", "Branch", "Attendance(%)", "CGPA", "Course Duration", "Address"};
            for (int i = 0; i < values.length; i++) {
                tModel.setValueAt(values[i], i, 0);
            }
            for (int i = 0; i < 12; i++) {
                tModel.setValueAt(null, i, 1);
            }
            if (rs.next() != false) {
                Blob blob = rs.getBlob("photo");
                byte[] imageData = blob.getBytes(1, (int) blob.length());
                // Create an Image object from the Blob data
                ImageIcon imageIcon = new ImageIcon(imageData);
                Image image = imageIcon.getImage();
                // Resize the Image if needed
                Image resizedImage = image.getScaledInstance(300, 300, Image.SCALE_SMOOTH);

                // Set the Image to the JLabel
                studentPhoto.setIcon(new ImageIcon(resizedImage));
                studentData.setPreferredSize(new Dimension(imageIcon.getIconWidth(), imageIcon.getIconHeight()));

                Object[] obj = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getDate(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getDouble(9), rs.getDouble(10), rs.getString(11), rs.getString(12)};
                for (int i = 0; i < obj.length; i++) {
                    tModel.setValueAt(obj[i], i, 1);
                }

            } else {
                studentPhoto.setText("Student Not Found");
                studentPhoto.setSize(12, 12);
            }

        } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, ex.getMessage());
        
        }
    }//GEN-LAST:event_checkBtnActionPerformed

    private void checkBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBackBtnActionPerformed
       adminPanelRef.adminHomePanel.remove(this);
       adminPanelRef.adminHomePanel.add(adminPanelRef.homePanel);
       adminPanelRef.adminHomePanel.repaint();
       adminPanelRef.adminHomePanel.revalidate();
    }//GEN-LAST:event_checkBackBtnActionPerformed

AdminPanel adminPanelRef=null;
        public void AdminPanelReference(AdminPanel adminPanelRef){
            this.adminPanelRef = adminPanelRef;
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkBackBtn;
    private javax.swing.JButton checkBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField rollNumberCheckField;
    private javax.swing.JLabel rollNumberLabel;
    private javax.swing.JTable studentData;
    private javax.swing.JLabel studentPhoto;
    // End of variables declaration//GEN-END:variables
}
