/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.studentbiodata;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Rahul
 */
public class RemoveStudentPanel extends javax.swing.JPanel {

    /**
     * Creates new form RemoveStudentPanel
     */
    public RemoveStudentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeStudentPanel = new javax.swing.JPanel();
        rollNumber = new javax.swing.JLabel();
        rollNumberToRemoveField = new javax.swing.JTextField();
        removeBtn = new javax.swing.JButton();
        removeStatus = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        rollNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rollNumber.setText("Roll Number");

        removeBtn.setText("remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        removeStatus.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        removeStatus.setForeground(new java.awt.Color(255, 0, 0));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeStudentPanelLayout = new javax.swing.GroupLayout(removeStudentPanel);
        removeStudentPanel.setLayout(removeStudentPanelLayout);
        removeStudentPanelLayout.setHorizontalGroup(
            removeStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeStudentPanelLayout.createSequentialGroup()
                .addGroup(removeStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeStudentPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(rollNumber)
                        .addGap(30, 30, 30)
                        .addComponent(rollNumberToRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removeStudentPanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(removeStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addGap(112, 112, 112)))
                .addGap(174, 174, 174))
            .addGroup(removeStudentPanelLayout.createSequentialGroup()
                .addGroup(removeStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeStudentPanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(removeBtn))
                    .addComponent(backBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        removeStudentPanelLayout.setVerticalGroup(
            removeStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeStudentPanelLayout.createSequentialGroup()
                .addComponent(backBtn)
                .addGap(21, 21, 21)
                .addGroup(removeStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollNumber)
                    .addComponent(rollNumberToRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(removeStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(removeBtn)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
            String query = "delete from studentBiodata where ROLLNUMBER = ?";
            ProcessData processData = new ProcessData(query);
            boolean status = processData.removeStudent( rollNumberToRemoveField.getText());

            if (status) {
                removeStatus.setText(rollNumberToRemoveField.getText() + " removed Successfully");
            } else {
                removeStatus.setText("No such roll number found..");
            } 
    }//GEN-LAST:event_removeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
       adminPanelRef.adminHomePanel.remove(this);
       adminPanelRef.adminHomePanel.add(adminPanelRef.homePanel);
        adminPanelRef.adminHomePanel.repaint();
        adminPanelRef.adminHomePanel.revalidate();
         
    }//GEN-LAST:event_backBtnActionPerformed
         AdminPanel adminPanelRef=null;
        public void AdminPanelReference(AdminPanel adminPanelRef){
            this.adminPanelRef = adminPanelRef;
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel removeStatus;
    private javax.swing.JPanel removeStudentPanel;
    private javax.swing.JLabel rollNumber;
    private javax.swing.JTextField rollNumberToRemoveField;
    // End of variables declaration//GEN-END:variables
}
