/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.studentbiodata;

import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Rahul
 */
public class UpdateStudentPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateStudentPanel
     */
    SetGetStudentData  setGetStudentData=null;
    public UpdateStudentPanel() {
        SetGetStudentData  setGetStudentData = new SetGetStudentData();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        updateStudentPane = new javax.swing.JScrollPane();
        updateStudentPanel1 = new javax.swing.JPanel();
        studentNameLabel = new javax.swing.JLabel();
        rollNumLabel = new javax.swing.JLabel();
        fatherNameLabel = new javax.swing.JLabel();
        motherNameLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        studentNameField1 = new javax.swing.JTextField();
        rollNumberField1 = new javax.swing.JTextField();
        fatherNameField1 = new javax.swing.JTextField();
        motherNameField1 = new javax.swing.JTextField();
        emailIdField1 = new javax.swing.JTextField();
        branchField1 = new javax.swing.JTextField();
        attendaceField1 = new javax.swing.JTextField();
        courseDurationField1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        addressField1 = new javax.swing.JTextArea();
        updateBtn = new javax.swing.JButton();
        male1 = new javax.swing.JRadioButton();
        female1 = new javax.swing.JRadioButton();
        others1 = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        gpaField1 = new javax.swing.JTextField();
        backBtn1 = new javax.swing.JButton();
        dateOfBirthField1 = new javax.swing.JTextField();
        updateRollNumberField = new javax.swing.JTextField();
        rollNumberLabel = new javax.swing.JLabel();
        checkUpdateBtn = new javax.swing.JButton();
        changePhotoBtn = new javax.swing.JButton();
        photoLabel = new javax.swing.JLabel();
        photoStudent = new javax.swing.JLabel();

        updateStudentPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        updateStudentPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        updateStudentPane.setName(""); // NOI18N

        updateStudentPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        updateStudentPanel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                updateStudentPanel1ComponentAdded(evt);
            }
        });

        studentNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studentNameLabel.setText("Student Name");

        rollNumLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rollNumLabel.setText("Roll Number");

        fatherNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fatherNameLabel.setText("Father Name");

        motherNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        motherNameLabel.setText("Mother Name");

        dobLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dobLabel.setText("Date of Birth");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Branch");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Attendance Percentage");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Course Duration");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Gender");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Address");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Email ID");

        studentNameField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentNameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameField1ActionPerformed(evt);
            }
        });

        rollNumberField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rollNumberField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollNumberField1ActionPerformed(evt);
            }
        });

        fatherNameField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fatherNameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherNameField1ActionPerformed(evt);
            }
        });

        motherNameField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        motherNameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motherNameField1ActionPerformed(evt);
            }
        });

        emailIdField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailIdField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdField1ActionPerformed(evt);
            }
        });

        branchField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        branchField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchField1ActionPerformed(evt);
            }
        });

        attendaceField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        attendaceField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendaceField1ActionPerformed(evt);
            }
        });

        courseDurationField1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023-2027", "2022-2026", "2021-2025 ", "2020-2024", "2019-2023 ", "2018-2022", "2017-2021 ", "2016-2020", "2015-2019" }));
        courseDurationField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseDurationField1ActionPerformed(evt);
            }
        });

        addressField1.setColumns(20);
        addressField1.setRows(5);
        addressField1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                addressField1InputMethodTextChanged(evt);
            }
        });
        jScrollPane3.setViewportView(addressField1);

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        gender.add(male1);
        male1.setText("Male");
        male1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                male1StateChanged(evt);
            }
        });

        gender.add(female1);
        female1.setText("Female");

        gender.add(others1);
        others1.setText("others");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Current CGPA");

        gpaField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaField1ActionPerformed(evt);
            }
        });

        backBtn1.setText("back");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        dateOfBirthField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfBirthField1ActionPerformed(evt);
            }
        });

        rollNumberLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        rollNumberLabel.setText("Roll Number : ");

        checkUpdateBtn.setText("check");
        checkUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkUpdateBtnActionPerformed(evt);
            }
        });

        changePhotoBtn.setText("Change Photo");
        changePhotoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePhotoBtnActionPerformed(evt);
            }
        });

        photoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        photoLabel.setText("Photo");

        photoStudent.setIcon(new javax.swing.ImageIcon("D:\\javaProjectEamcet\\studentBioData\\src\\images\\emptyPhoto.jpg")); // NOI18N
        photoStudent.setMinimumSize(new java.awt.Dimension(300, 300));
        photoStudent.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout updateStudentPanel1Layout = new javax.swing.GroupLayout(updateStudentPanel1);
        updateStudentPanel1.setLayout(updateStudentPanel1Layout);
        updateStudentPanel1Layout.setHorizontalGroup(
            updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                                .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rollNumLabel)
                                    .addComponent(fatherNameLabel)
                                    .addComponent(motherNameLabel)
                                    .addComponent(dobLabel)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27)
                                    .addComponent(studentNameLabel))
                                .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(changePhotoBtn)
                                    .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                                        .addComponent(male1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(female1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(others1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(courseDurationField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rollNumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fatherNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(motherNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailIdField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateOfBirthField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(branchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(attendaceField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gpaField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                                .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(checkUpdateBtn)
                                        .addGap(70, 70, 70))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateStudentPanel1Layout.createSequentialGroup()
                                        .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)))
                                .addGap(3, 3, 3)
                                .addComponent(photoStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                        .addComponent(rollNumberLabel)
                        .addGap(37, 37, 37)
                        .addComponent(updateRollNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn1))
                    .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(updateBtn)))
                .addGap(813, 813, 813))
        );

        updateStudentPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {attendaceField1, branchField1, courseDurationField1, dateOfBirthField1, emailIdField1, fatherNameField1, gpaField1, motherNameField1, rollNumberField1, studentNameField1});

        updateStudentPanel1Layout.setVerticalGroup(
            updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollNumberLabel)
                    .addComponent(updateRollNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                        .addGap(18, 61, Short.MAX_VALUE)
                        .addComponent(photoStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(changePhotoBtn))
                    .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(checkUpdateBtn)
                        .addGap(98, 98, 98)
                        .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(4, 4, 4)
                .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNameLabel)
                    .addComponent(studentNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollNumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rollNumLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fatherNameLabel)
                    .addComponent(fatherNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motherNameLabel)
                    .addComponent(motherNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                        .addComponent(dobLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(male1)
                            .addComponent(female1)
                            .addComponent(others1))
                        .addGap(18, 18, 18)
                        .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(emailIdField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(branchField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attendaceField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(gpaField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(courseDurationField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(updateStudentPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(dateOfBirthField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateStudentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateBtn)
                .addContainerGap())
        );

        updateStudentPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {attendaceField1, branchField1, courseDurationField1, dateOfBirthField1, emailIdField1, fatherNameField1, gpaField1, motherNameField1, rollNumberField1, studentNameField1});

        updateStudentPane.setViewportView(updateStudentPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateStudentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateStudentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void studentNameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameField1ActionPerformed

    private void rollNumberField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollNumberField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollNumberField1ActionPerformed

    private void fatherNameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherNameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherNameField1ActionPerformed

    private void motherNameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherNameField1ActionPerformed

    }//GEN-LAST:event_motherNameField1ActionPerformed

    private void emailIdField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdField1ActionPerformed

    }//GEN-LAST:event_emailIdField1ActionPerformed

    private void branchField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchField1ActionPerformed

    }//GEN-LAST:event_branchField1ActionPerformed

    private void attendaceField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendaceField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendaceField1ActionPerformed

    private void courseDurationField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseDurationField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseDurationField1ActionPerformed

    private void addressField1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_addressField1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_addressField1InputMethodTextChanged
    
        boolean changePhotoStatus = false;
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        
        setGetStudentData.setName(studentNameField1.getText());
        setGetStudentData.setRollNumber(rollNumberField1.getText());
        setGetStudentData.setFatherName(fatherNameField1.getText());
        setGetStudentData.setMotherName(motherNameField1.getText());
        setGetStudentData.setDateOfBirth(dateOfBirthField1.getText());
        setGetStudentData.setEmail(emailIdField1.getText());
        setGetStudentData.setBranch(branchField1.getText());
        if(attendaceField1.getText().isEmpty()){
             setGetStudentData.setAttendancePercentage(0.0);
        }else{
        setGetStudentData.setAttendancePercentage(Double.parseDouble(attendaceField1.getText()));
        }
        if(gpaField1.getText().isEmpty()){
             setGetStudentData.setCgpa(0.0);
        }else{
        setGetStudentData.setCgpa(Double.parseDouble(gpaField1.getText()));
        }
        setGetStudentData.setAddress(addressField1.getText());
        setGetStudentData.setCourseDuration((String) courseDurationField1.getSelectedItem());

        Enumeration<AbstractButton> buttons = gender.getElements();
        while (buttons.hasMoreElements()) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                setGetStudentData.setGender(button.getText());
                break;
            }
        }
        ProcessData processData = new ProcessData();
        
        if(changePhotoStatus){
            
            if (processData.nullCheck(setGetStudentData)) {
                    String query = "UPDATE STUDENTBIODATA SET "
                    + "NAME = ?, "
                    + "FATHERNAME = ?, "
                    + "MOTHERNAME = ?, "
                    + "DATEOFBIRTH = ?, "
                    + "GENDER = ?, "
                    + "EMAIL = ?, "
                    + "BRANCH = ?, "
                    + "ATTENDANCEPERCENTAGE = ?, "
                    + "CGPA = ?, "
                    + "COURSEDURATION = ?, "
                    + "ADDRESS = ?, "
                    + "PHOTO = ? "
                    + "WHERE ROLLNUMBER = ?";
                    processData.setPreparedStatement(query);
                 
                   boolean status = processData.addStudent(setGetStudentData);
                    if (status) {
                        JOptionPane.showMessageDialog(null, "Data successfully saved.");
                    } else {
                       JOptionPane.showMessageDialog(null, "Data not saved");
                    }
            }
            else {
                JOptionPane.showMessageDialog(null, "Enter all Fields to Save");
            }
        }
        else{
            if (setGetStudentData.getName() != null
                && setGetStudentData.getRollNumber() != null
                && setGetStudentData.getFatherName() != null
                && setGetStudentData.getMotherName() != null
                && setGetStudentData.getDateOfBirth() != null
                && setGetStudentData.getGender() != null
                && setGetStudentData.getEmail() != null
                && setGetStudentData.getBranch() != null
                && setGetStudentData.getAttendancePercentage() != 0
                && setGetStudentData.getCgpa() != 0
                && setGetStudentData.getCourseDuration() != null
                && setGetStudentData.getAddress() != null) {
                try {
                    Connection con = GetConnection.createConnection();

                    String query = "UPDATE STUDENTBIODATA SET "
                    + "NAME = ?, "
                    + "FATHERNAME = ?, "
                    + "MOTHERNAME = ?, "
                    + "DATEOFBIRTH = ?, "
                    + "GENDER = ?, "
                    + "EMAIL = ?, "
                    + "BRANCH = ?, "
                    + "ATTENDANCEPERCENTAGE = ?, "
                    + "CGPA = ?, "
                    + "COURSEDURATION = ?, "
                    + "ADDRESS = ? "
                    + "WHERE ROLLNUMBER = ?";
                    PreparedStatement preparedStatement = con.prepareStatement(query);
                    preparedStatement.setString(1, setGetStudentData.getName());
                    preparedStatement.setString(12, setGetStudentData.getRollNumber());
                    preparedStatement.setString(2, setGetStudentData.getFatherName());
                    preparedStatement.setString(3, setGetStudentData.getMotherName());
                    preparedStatement.setString(4, setGetStudentData.getDateOfBirth());
                    preparedStatement.setString(5, setGetStudentData.getGender());
                    preparedStatement.setString(6, setGetStudentData.getEmail());
                    preparedStatement.setString(7, setGetStudentData.getBranch());
                    preparedStatement.setDouble(8, setGetStudentData.getAttendancePercentage());
                    preparedStatement.setDouble(9, setGetStudentData.getCgpa());
                    preparedStatement.setString(10, setGetStudentData.getCourseDuration());
                    preparedStatement.setString(11, setGetStudentData.getAddress());
                    int x = preparedStatement.executeUpdate();
                    if (x == 1) {
                        JOptionPane.showMessageDialog(null, "Data successfully saved.");
                    } else {
                        throw new SQLException("Error something went wrong!!!");
                    }

                } catch (Exception s) {
                    JOptionPane.showMessageDialog(null, "Unexcepted-Error");
                    adminPanelRef.dispose();
                    s.printStackTrace();
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Enter all Fields to Save");
            }
        }

    }//GEN-LAST:event_updateBtnActionPerformed

    private void male1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_male1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_male1StateChanged

    private void gpaField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaField1ActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
       adminPanelRef.adminHomePanel.remove(this);
       adminPanelRef.adminHomePanel.add(adminPanelRef.homePanel);
       adminPanelRef.adminHomePanel.repaint();
       adminPanelRef.adminHomePanel.revalidate();
    }//GEN-LAST:event_backBtn1ActionPerformed

AdminPanel adminPanelRef=null;
        public void AdminPanelReference(AdminPanel adminPanelRef){
            this.adminPanelRef = adminPanelRef;
        }
    private void dateOfBirthField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfBirthField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOfBirthField1ActionPerformed

    private void checkUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkUpdateBtnActionPerformed
        setGetStudentData = new SetGetStudentData();
        try {
            String rollNumber = updateRollNumberField.getText();
            Connection con = GetConnection.createConnection();
            String query = "Select * from studentbiodata where rollNumber = ?";
            PreparedStatement statement = con.prepareStatement(query);
            statement.setString(1, rollNumber);
            ResultSet rs = statement.executeQuery();
            if (rs.next() != false) {
                System.out.println(rs);
                Object[] obj = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getDate(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getDouble(9), rs.getDouble(10), rs.getString(11), rs.getString(12)};
                setGetStudentData.setName((String) obj[0]);
                setGetStudentData.setRollNumber((String) obj[1]);
                setGetStudentData.setFatherName((String) obj[2]);
                setGetStudentData.setMotherName((String) obj[3]);
                Date date = (Date) obj[4];
                String pattern = "dd-MM-yyyy";
                SimpleDateFormat sdf = new SimpleDateFormat(pattern);
                setGetStudentData.setDateOfBirth(sdf.format(date));
                setGetStudentData.setEmail((String) obj[6]);
                setGetStudentData.setBranch((String) obj[7]);
                setGetStudentData.setAttendancePercentage((double) obj[8]);
                setGetStudentData.setCgpa((double) obj[9]);
                setGetStudentData.setAddress((String) obj[11]);
                setGetStudentData.setCourseDuration((String) obj[10]);

                switch ((String)obj[5]) {
                    case "Male":
                    male1.setSelected(true);
                    setGetStudentData.setGender("Male");
                    break;
                    case "Female":
                    female1.setSelected(true);
                    setGetStudentData.setGender("Male");
                    break;
                    case "others":
                    others1.setSelected(true);
                    setGetStudentData.setGender("Male");
                    break;
                }

                Blob blob = rs.getBlob("photo");
                byte[] imageData = blob.getBytes(1, (int) blob.length());

                ImageIcon imageIcon = new ImageIcon(imageData);
                Image image = imageIcon.getImage();

                Image resizedImage = image.getScaledInstance(300, 300, Image.SCALE_SMOOTH);

                photoStudent.setIcon(new ImageIcon(resizedImage));
                photoStudent.setPreferredSize(new Dimension(imageIcon.getIconWidth(), imageIcon.getIconHeight()));
                studentNameField1.setText(setGetStudentData.getName());
                rollNumberField1.setText(setGetStudentData.getRollNumber());
                fatherNameField1.setText(setGetStudentData.getFatherName());
                motherNameField1.setText(setGetStudentData.getMotherName());
                dateOfBirthField1.setText(setGetStudentData.getDateOfBirth());
                emailIdField1.setText(setGetStudentData.getEmail());
                branchField1.setText(setGetStudentData.getBranch());
                attendaceField1.setText(String.valueOf(setGetStudentData.getAttendancePercentage()));
                gpaField1.setText(String.valueOf(setGetStudentData.getCgpa()));
                courseDurationField1.setSelectedItem(setGetStudentData.getCourseDuration());
                addressField1.setText(setGetStudentData.getAddress());

            }
            else{
                JOptionPane.showMessageDialog(null, "Roll Number does not exist");
                updateRollNumberField.setText(null);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_checkUpdateBtnActionPerformed

    private void changePhotoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePhotoBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
         ArrayList<String> ALLOWED_EXTENSIONS = new ArrayList<String>();
         ALLOWED_EXTENSIONS.add(".jpg");
         ALLOWED_EXTENSIONS.add(".jpeg");
         ALLOWED_EXTENSIONS.add(".png");
         ALLOWED_EXTENSIONS.add(".gif");
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            ProcessData pd = new ProcessData();
            String extension = pd.getFileExtension(selectedFile.getAbsolutePath());
            try{
            if (!ALLOWED_EXTENSIONS.contains(extension.toLowerCase())) {
                throw new IllegalArgumentException("Photo Format Error");
            }
            else{
            try {
                ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
                Image image = imageIcon.getImage();
                Image resizedImage = image.getScaledInstance(300, 300, Image.SCALE_SMOOTH);
                photoStudent.setIcon(new ImageIcon(resizedImage));
                changePhotoBtn.setText(selectedFile.getPath());
                uploadPhotoToDatabase(selectedFile);
                changePhotoStatus = true;
            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null, "Error:  " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } 
            catch(IOException ioe){
                
            }
        }}catch(IllegalArgumentException iae){
            changePhotoBtn.setText("Change Photo");
            setGetStudentData.setPhotoPath(null);
              JOptionPane.showMessageDialog(null, "Error:  " + iae.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_changePhotoBtnActionPerformed

    private void updateStudentPanel1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_updateStudentPanel1ComponentAdded

    }//GEN-LAST:event_updateStudentPanel1ComponentAdded
private void uploadPhotoToDatabase(File selectedFile) throws SQLException, IOException  {       
        try {
            FileInputStream studentPhotoFile = new FileInputStream(selectedFile);
            setGetStudentData.setPhotoPath(studentPhotoFile);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressField1;
    private javax.swing.JTextField attendaceField1;
    private javax.swing.JButton backBtn1;
    private javax.swing.JTextField branchField1;
    private javax.swing.JButton changePhotoBtn;
    private javax.swing.JButton checkUpdateBtn;
    private javax.swing.JComboBox<String> courseDurationField1;
    private javax.swing.JTextField dateOfBirthField1;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField emailIdField1;
    private javax.swing.JTextField fatherNameField1;
    private javax.swing.JLabel fatherNameLabel;
    private javax.swing.JRadioButton female1;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JTextField gpaField1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton male1;
    private javax.swing.JTextField motherNameField1;
    private javax.swing.JLabel motherNameLabel;
    private javax.swing.JRadioButton others1;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel photoStudent;
    private javax.swing.JLabel rollNumLabel;
    private javax.swing.JTextField rollNumberField1;
    private javax.swing.JLabel rollNumberLabel;
    private javax.swing.JTextField studentNameField1;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField updateRollNumberField;
    private javax.swing.JScrollPane updateStudentPane;
    private javax.swing.JPanel updateStudentPanel1;
    // End of variables declaration//GEN-END:variables
}
